### ISSUE TITLE
Ecma 262 Validation for patterns

### ISSUE THREAD

**Issue by maier-stefan** [davishmcclurg/json_schemer#101]
I am currently run into an issue with ruby and javascript.
So basically i had some pattern in my ruby codebase that were not 100% with ecma but fine for ruby.

For example:

`"^today+([-+][0-9]*d)?+$" # does not work with ecma 262`

`"^(today+([-+][0-9]*d)?)+$" # works with ecma 262`

When looking into the codebase
https://github.com/davishmcclurg/json_schemer/blob/ab5ea07e21633952f5025aaabcfbb37c05c3a74d/lib/json_schemer/schema/base.rb#L402

I wonder if it would also make sense to validate this pattern like we do the format in https://github.com/davishmcclurg/json_schemer/blob/ab5ea07e21633952f5025aaabcfbb37c05c3a74d/lib/json_schemer/format.rb#L49

**Comment by davishmcclurg** [comment]
Hi @maier-stefan—thanks for the issue. In general, I've tried to avoid validating the schema while validating data for performance reasons. It's possible to use the same schema object (and underlying JSON schema) many times with different data and validating the schema really only needs to happen once.

One way to handle this is by validating the schema against its [meta schema](https://json-schema.org/draft-07/schema), for example:

```
% bin/console --simple-prompt -r open-uri
>> JSONSchemer.schema(URI('https://json-schema.org/draft-07/schema').read).valid?('pattern' => "^today+([-+][0-9]*d)?+$")
=> false
>> JSONSchemer.schema(URI('https://json-schema.org/draft-07/schema').read).valid?('pattern' => "^(today+([-+][0-9]*d)?)+$")
=> true
```

There's an open issue that addresses invalid schemas: https://github.com/davishmcclurg/json_schemer/issues/80 The approach discussed there is adding a `valid_schema?` method of some kind, but it hasn't been implemented yet. Let me know if you're interested!

I'm going to close this since I believe it's covered in the existing issue. Feel free to reopen if you disagree. Thanks!
