### ISSUE TITLE
Lacking support for deprecated fields

### ISSUE THREAD

**Issue by galtomer** [davishmcclurg/json_schemer#155]
When using a JSON schema that contains deprecated fields, JSON Schemer does not consider them as an issue upon validation.

### Example

Consider this schema:
```json
{
    "type": "object",
    "additionalProperties": false,
    "required": [
        "environments"
    ],
    "properties": {
        "environments": {
            "clusters": {
                "type": "array",
                "description": "`clusters` property is deprecated, please use `cluster_selector` instead.",
                "deprecated": true,
                "items": {
                    "type": "string"
                }
            }
        }
    }
}

```

And the following YAML to validate against it:
```yaml
environments:
  - name: production
    clusters:
      - foo
```

Using JSON Schemer in the following manner:
```ruby
schema = JSON.parse(File.read(schema_json_path))
schemer = JSONSchemer.schema(schema)
response = schemer.validate(yaml_config)
```

### Expected behaviour

You would expect JSON Schemer to raise an issue for the given YAML and schema:
```
`clusters` property is deprecated, please use `cluster_selector` instead.
```

### Actual behaviour

JSON Schemer does not return any issues.

**Comment by davishmcclurg** [comment]
As far as I understand, neither [json schema](https://json-schema.org/draft/2020-12/json-schema-validation#section-9.3) or [openapi](https://spec.openapis.org/oas/v3.1.0) specify that `deprecated` should cause validation to fail. If you use an output format, you will get a `deprecated` annotation back for successful validations:

```
?> schema = {
?>   'properties' => {
?>     'x' => {
?>       'deprecated' => true
?>     }
?>   }
>> }
=> {"properties"=>{"x"=>{"deprecated"=>true}}}
?> instance = {
?>   'x' => 1
>> }
=> {"x"=>1}
>> JSONSchemer.schema(schema).validate(instance, output_format: 'basic').fetch('annotations').to_a
=> [{"valid"=>true, "keywordLocation"=>"/properties/x/deprecated", "absoluteKeywordLocation"=>"json-schemer://schema#/properties/x/deprecated", "instanceLocation"=>"/x", "annotation"=>true}]
```

But that's about it. I don't think it makes sense to always return an error for `deprecated` since deprecated features are usually still useful (and supported) while people migrate to whatever is replacing them.

Are you expecting an error? Or is there another way to handle `deprecated` that you'd like to see?
