### ISSUE TITLE
Nullable not working correctly when using `$ref`

### ISSUE THREAD

**Issue by bilby91** [davishmcclurg/json_schemer#199]
Hello @davishmcclurg!

I stumble upon this issue where `nullable: true` is not honored when used in a field declared with `$ref`. This is my exact example.

```
Volume:
      type: object
      description: A representation of a volume in the system, which can be attached to virtual machines.
      properties:
        id:
          type: integer
          format: int32
          description: The unique identifier of the volume.
          example: 1
        object:
          type: string
          enum: [volume]
          description: The object type, which is always "volume" for volumes.
        name:
          type: string
          description: The name of the volume.
          example: swagger-vol
        size_bytes:
          type: integer
          format: int64
          description: The size of the volume, in bytes.
          example: 10737418240
        status:
          type: string
          description: The current operational status of the volume.
          example: in_use
          enum:
            - creating
            - in_use
            - available
            - deleting
        volume_attachment:
          nullable: true
          $ref: '#/components/schemas/VolumeAttachment'
  ```
  
  I have created a test that reproduces the problem, the last `assert` is not passing when it should IMO => https://github.com/bilby91/json_schemer/blob/8097bd3d9a497a6803c71d31cd5bf23bf7326372/test/open_api_test.rb#L1119
  
  I've also found a typescript implementation where they are handling this "correctly" => https://github.com/acacode/swagger-typescript-api/pull/40

**Comment by bilby91** [comment]
@davishmcclurg I was able to get the test passing without breaking any other test. Here is the PR => https://github.com/davishmcclurg/json_schemer/pull/200

I know that the PR might need adjustment since I'm impacting `draft202012` instead of OpenAPI 3.0 but I wasn't able to figure out how to hook the type yet.

**Comment by dgholz** [comment]
nice, I just hit this

**Comment by davishmcclurg** [comment]
Hi @bilby91, thanks for reporting this and for taking the time put together a fix. Unfortunately, I think this is expected behavior. From the [OpenAPI 3.0 specification section on `$ref`][0]:

> This object cannot be extended with additional properties and any properties added SHALL be ignored.

OpenAPI 3.0 is based on JSON Schema Draft 4, which uses ["JSON Reference"][1]:

> Any members other than "$ref" in a JSON Reference object SHALL be ignored.

[0]: https://spec.openapis.org/oas/v3.0.3.html#fixed-fields-18
[1]: https://datatracker.ietf.org/doc/html/draft-pbryan-zyp-json-ref-03#section-3

Same behavior in draft 4:

```
?> schema = JSONSchemer.schema(
?>   {
?>     '$ref' => '#/definitions/example',
?>     'minLength' => 2,
?>     'definitions' => {
?>       'example' => {
?>         'type' => 'string',
?>         'maxLength' => 2
?>       }
?>     }
?>   },
?>   :meta_schema => JSONSchemer.draft4
>> )
=> #<JSONSchemer::Schema @value={"$ref"=>"#/definitions/example", "minLength"=>2, "definitions"=>{"example"=>{"type"=>"string", "maxLength"=>2}}} @parent=nil @keyword=nil>
>> schema.valid?('x')
=> true
>> schema.valid?('xx')
=> true
>> schema.valid?('xxx')
=> false
```

Feel free to reopen if you'd like to discuss further.

**Comment by dgholz** [comment]
I was aware of the restriction with `$ref` and sibling properties, so I was using `allOf` to combine the `$ref` & `nullable` with a schema like:
```
{
  'type' => 'object',
  'properties' => {
    'example' => {
      'nullable' => true,
      'allOf' => [
        {
          '$ref' => '#/definitions/example'
        }
      ]
    }
  },
  'definitions' => {
    'example' => {
      'type' => 'string'
    }
  }
}
```

but I see with the ref removed (and the definition moved inline), the validation still fails. So it's not caused by combining `$ref` and `nullable`.

I checked some other tools and see they also say `{ 'example' => nil }` is invalid, at least from Draft 4 onwards.
